CREATE SEQUENCE SEQ_POST;

CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(1000) NOT NULL,
	POST_CONTENT VARCHAR2(1000) NOT NULL,
	POST_READ_COUNT NUMBER DEFAULT 0,
	MEMBER_ID NUMBER NOT NULL,
	CREATED_DATE DATE DEFAULT SYSDATE,
	UPDATED_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_POST_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);
SELECT P.ID, P.POST_TITLE, P.POST_CONTENT, P.POST_READ_COUNT, P.CREATED_DATE, P.UPDATED_DATE, M.ID, M.MEMBER_EMAIL, M.MEMBER_PASSWORD, M.MEMBER_NAME, M.MEMBER_AGE, M.MEMBER_GENDER, M.CREATED_DATE, M.UPDATED_DATE FROM TBL_POST P JOIN TBL_MEMBER M ON P.MEMBER_ID = M.ID;
SELECT * FROM TBL_MEMBER;
SELECT ROWNUM FROM TBL_POST; 

SELECT * FROM TBL_ADMIN;

/*INSERT INTO TBL_POST
(ID, POST_TITLE, POST_CONTENT, MEMBER_ID)
(SELECT SEQ_POST.NEXTVAL, POST_TITLE, POST_CONTENT, MEMBER_ID FROM TBL_POST);*/

SELECT COUNT(*) FROM TBL_POST;
