CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
   ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
   REPLY_CONTENT VARCHAR2(1000) NOT NULL,
   POST_ID NUMBER NOT NULL,
   MEMBER_ID NUMBER NOT NULL,
   CREATED_DATE DATE DEFAULT SYSDATE,
   UPDATED_DATE DATE DEFAULT SYSDATE,
   CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
   REFERENCES TBL_POST(ID),
   CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID)
);

SELECT ID, REPLY_CONTENT, POST_ID, MEMBER_ID, CREATED_DATE, UPDATED_DATE FROM TBL_REPLY;

SELECT * FROM TBL_REPLY;

SELECT R.ID, R.REPLY_CONTENT, R.POST_ID, R.MEMBER_ID, R.CREATED_DATE, R.UPDATED_DATE, P.POST_TITLE, M.MEMBER_NAME  FROM TBL_REPLY R JOIN TBL_POST P ON R.POST_ID = P.ID JOIN TBL_MEMBER M ON P.MEMBER_ID = M.ID;